# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(20, 20, 31, 34))
        self.id_label.setObjectName("id_label")
        self.id_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.id_spinbox.setGeometry(QtCore.QRect(50, 20, 131, 34))
        self.id_spinbox.setMaximum(999)
        self.id_spinbox.setObjectName("id_spinbox")
        self.kind_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.kind_combobox.setGeometry(QtCore.QRect(260, 22, 161, 34))
        self.kind_combobox.setObjectName("kind_combobox")
        self.kind_label = QtWidgets.QLabel(self.centralwidget)
        self.kind_label.setGeometry(QtCore.QRect(190, 20, 41, 39))
        self.kind_label.setObjectName("kind_label")
        self.roasting_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.roasting_combobox.setGeometry(QtCore.QRect(260, 60, 161, 34))
        self.roasting_combobox.setObjectName("roasting_combobox")
        self.roasting_label = QtWidgets.QLabel(self.centralwidget)
        self.roasting_label.setGeometry(QtCore.QRect(190, 58, 70, 39))
        self.roasting_label.setObjectName("roasting_label")
        self.condition_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.condition_combobox.setGeometry(QtCore.QRect(490, 60, 171, 34))
        self.condition_combobox.setObjectName("condition_combobox")
        self.condition_label = QtWidgets.QLabel(self.centralwidget)
        self.condition_label.setGeometry(QtCore.QRect(430, 58, 61, 39))
        self.condition_label.setObjectName("condition_label")
        self.price_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.price_spinbox.setGeometry(QtCore.QRect(80, 62, 107, 34))
        self.price_spinbox.setMaximum(999)
        self.price_spinbox.setObjectName("price_spinbox")
        self.price_label = QtWidgets.QLabel(self.centralwidget)
        self.price_label.setGeometry(QtCore.QRect(20, 60, 60, 39))
        self.price_label.setObjectName("price_label")
        self.size_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.size_spinbox.setGeometry(QtCore.QRect(540, 20, 124, 34))
        self.size_spinbox.setMaximum(23999)
        self.size_spinbox.setObjectName("size_spinbox")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(430, 18, 100, 39))
        self.size_label.setObjectName("size_label")
        self.table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.table_widget.setGeometry(QtCore.QRect(10, 120, 741, 411))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(670, 20, 81, 31))
        self.search_btn.setObjectName("search_btn")
        self.control_btn = QtWidgets.QPushButton(self.centralwidget)
        self.control_btn.setGeometry(QtCore.QRect(670, 60, 81, 34))
        self.control_btn.setObjectName("control_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Найдите подходящий Вам кофе"))
        self.id_label.setText(_translate("MainWindow", "ID:"))
        self.kind_label.setText(_translate("MainWindow", "Сорт:"))
        self.roasting_label.setText(_translate("MainWindow", "Обжарка:"))
        self.condition_label.setText(_translate("MainWindow", "Форма:"))
        self.price_label.setText(_translate("MainWindow", "Цена(р):"))
        self.size_label.setText(_translate("MainWindow", "Объём(см^2):"))
        self.search_btn.setText(_translate("MainWindow", "Найти"))
        self.control_btn.setText(_translate("MainWindow", "Контроль"))
